### ISSUE TITLE
Related work

### ISSUE THREAD

**Issue by Laurian** [w3ctag/capability-urls#1]
Tyler Close: 

Web-Key: Mashing with permission
http://waterken.sourceforge.net/web-key/

Also he has an interesting older implementation in his Waterken server http://www.waterken.com/dev/Web/Calculus/ 

And a very interesting capability delegation (yurl) idea http://www.waterken.com/dev/YURL/httpsy/

Also see: Capability Theory by Sound Bytes http://www.cap-lore.com/CapTheory/

**Comment by metaweta** [comment]
In particular, if the secret bits are wholly contained in the fragment, they will not be sent as part of the referrer.  The recommendation "Pages accessed through a capability URL should not include links to third-party websites, or to untrusted third-party scripts" is only relevant if the secret bits are not wholly contained in the fragment.  

Web-keys refer to a cacheable javascript page that retrieves the bits from the fragment and submits them as part of an HTTPS POST.

**Comment by torgo** [comment]
Thank you for your input we are not updating this document at this time.
