### ISSUE TITLE
Tahoe-LAFS

### ISSUE THREAD

**Issue by zooko** [w3ctag/capability-urls#2]
Folks: the “Tahoe” Least-Authority File System has been using this pattern for many years:

https://tahoe-lafs.org/trac/tahoe-lafs/browser/trunk/docs/frontends/webapi.rst

(Also on github: https://github.com/tahoe-lafs/tahoe-lafs/blob/master/docs/frontends/webapi.rst )

We've gained some useful experience from practicing this approach, including finding and fixing security problems. I'd be happy to contribute what I know to the capability-urls document.

**Comment by JeniT** [comment]
Please do, that would be great!

**Comment by zooko** [comment]
Dear JeniT: could you please cite Tahoe-LAFS as an example of this pattern in the document? Here is an example of it that is publicly visible: https://zooko.com/uri/URI:DIR2-MDMF-RO:dwvqalbdt4ax4vgupcewxljg3u:bej7hhojmpuugy77oyydmazf6uu7huiipkctih7adky7e6txavnq/klog.html

**Comment by zooko** [comment]
Here is a peer-reviewed paper about Tahoe-LAFS: http://eprint.iacr.org/2012/524
