### ISSUE TITLE
Document implies that outbound links are unsafe

### ISSUE THREAD

**Issue by martinthomson** [w3ctag/capability-urls#8]
> Pages accessed through a capability URL should not include links to third-party websites [...]

This is misleading, because the [HTTP spec](http://httpwg.org/specs/rfc7231.html#header.referer) requires that Referer not be sent:

> A user agent MUST NOT send a Referer header field in an unsecured HTTP request if the referring page was received with a secure protocol.

What the document should say is that if a different referer policy is set by the resource, it should not include rules that allow the secret part of the URL to be leaked to third parties (and then explain how to do that).

**Comment by annevk** [comment]
@martinthomson why would the outbound link not use HTTPS though?

**Comment by martinthomson** [comment]
:facepalm:
